package com.instantchatbot.service;

import com.instantchatbot.entity.GeneratedBot;
import com.instantchatbot.entity.Project;
import com.instantchatbot.exception.ResourceNotFoundException;
import com.instantchatbot.repository.GeneratedBotRepository;
import com.instantchatbot.repository.ProjectRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.*;
import java.nio.file.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * Service responsible for generating a standalone chatbot package (ZIP).
 * The package includes a FastAPI server, a React-based chat widget, and
 * configuration templates for deployment.
 */
@Service
public class CodeGeneratorService {

    private static final Logger log = LoggerFactory.getLogger(CodeGeneratorService.class);

    @Value("${storage.zip-path}")
    private String zipStoragePath;

    private final ProjectRepository projectRepository;
    private final GeneratedBotRepository generatedBotRepository;

    /**
     * Constructs the CodeGeneratorService with required repositories.
     *
     * @param projectRepository the repository for accessing project metadata
     * @param generatedBotRepository the repository for storing generation metadata
     */
    public CodeGeneratorService(ProjectRepository projectRepository,
                                 GeneratedBotRepository generatedBotRepository) {
        this.projectRepository = projectRepository;
        this.generatedBotRepository = generatedBotRepository;
    }

    /**
     * Generates a complete chatbot package for a project.
     * This involves creating temporary files, bundling code templates, and creating a ZIP archive.
     *
     * @param projectId the identifier of the project to generate for
     * @throws IOException if file system operations fail
     * @throws ResourceNotFoundException if the project is not found
     */
    @Transactional
    public void generateChatbot(Long projectId) throws IOException {
        Project project = projectRepository.findById(projectId)
                .orElseThrow(() -> new ResourceNotFoundException("Project not found"));

        log.info("Generating chatbot code for project: {}", projectId);

        // Create temp directory for generated code
        Path tempDir = Files.createTempDirectory("chatbot-" + projectId);
        Path serverDir = tempDir.resolve("chatbot-server");
        Files.createDirectories(serverDir);
        Files.createDirectories(serverDir.resolve("app"));

        // Generate main FastAPI server
        generateMainPy(serverDir, projectId);
        generateRequirementsTxt(serverDir);
        generateEnvExample(serverDir, projectId);
        generateDockerfile(serverDir);
        generateReadme(serverDir, project);
        generateWidget(serverDir);
        generateDeployScript(serverDir);

        // Create ZIP
        Path zipDir = Paths.get(zipStoragePath);
        Files.createDirectories(zipDir);
        Path zipFile = zipDir.resolve("chatbot-" + projectId + ".zip");
        createZip(serverDir, zipFile);

        long fileSize = Files.size(zipFile);

        // Save generated bot record
        GeneratedBot bot = project.getGeneratedBot();
        if (bot == null) {
            bot = GeneratedBot.builder()
                    .project(project)
                    .zipFilePath(zipFile.toString())
                    .fileSizeBytes(fileSize)
                    .build();
        } else {
            bot.setZipFilePath(zipFile.toString());
            bot.setFileSizeBytes(fileSize);
        }
        generatedBotRepository.save(bot);

        // Cleanup temp directory
        deleteDirectory(tempDir);
        log.info("Chatbot ZIP generated: {} ({} bytes)", zipFile, fileSize);
    }

    private void generateMainPy(Path dir, Long projectId) throws IOException {
        String content = """
                \"\"\"
                AI Chatbot Server - Auto-generated by Instant Chatbot Platform
                \"\"\"
                import os
                from fastapi import FastAPI, HTTPException
                from fastapi.middleware.cors import CORSMiddleware
                from pydantic import BaseModel
                import chromadb
                from openai import OpenAI
                from dotenv import load_dotenv
                
                load_dotenv()
                
                app = FastAPI(title="AI Chatbot", version="1.0.0")
                
                app.add_middleware(
                    CORSMiddleware,
                    allow_origins=["*"],
                    allow_credentials=True,
                    allow_methods=["*"],
                    allow_headers=["*"],
                )
                
                # Initialize OpenAI client
                client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
                
                # Initialize ChromaDB
                chroma_client = chromadb.PersistentClient(path=os.getenv("CHROMA_PATH", "./chroma_db"))
                collection = chroma_client.get_or_create_collection(name="project_%s")
                
                
                class ChatMessage(BaseModel):
                    message: str
                
                
                class ChatResponse(BaseModel):
                    answer: str
                    sources: list[str] = []
                
                
                @app.post("/chat", response_model=ChatResponse)
                async def chat(msg: ChatMessage):
                    try:
                        # Generate embedding for query
                        query_embedding = client.embeddings.create(
                            input=msg.message,
                            model="text-embedding-3-small"
                        ).data[0].embedding
                
                        # Retrieve relevant chunks
                        results = collection.query(
                            query_embeddings=[query_embedding],
                            n_results=5
                        )
                
                        context_chunks = results["documents"][0] if results["documents"] else []
                        sources = results["metadatas"][0] if results["metadatas"] else []
                
                        context = "\\n\\n".join(context_chunks)
                
                        # Generate response
                        completion = client.chat.completions.create(
                            model="gpt-4o-mini",
                            messages=[
                                {
                                    "role": "system",
                                    "content": f"You are a helpful assistant. Answer based on the following context. "
                                               f"If the answer is not in the context, say so.\\n\\nContext:\\n{context}"
                                },
                                {"role": "user", "content": msg.message}
                            ],
                            max_tokens=500,
                            temperature=0.7,
                        )
                
                        source_urls = [s.get("url", "") for s in sources if isinstance(s, dict)]
                
                        return ChatResponse(
                            answer=completion.choices[0].message.content,
                            sources=list(set(source_urls))
                        )
                
                    except Exception as e:
                        raise HTTPException(status_code=500, detail=str(e))
                
                
                @app.get("/health")
                async def health():
                    return {"status": "healthy"}
                
                
                if __name__ == "__main__":
                    import uvicorn
                    uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("PORT", "8001")))
                """.formatted(projectId);

        Files.writeString(dir.resolve("main.py"), content);
    }

    private void generateRequirementsTxt(Path dir) throws IOException {
        String content = """
                fastapi==0.110.0
                uvicorn==0.27.1
                openai==1.12.0
                chromadb==0.4.22
                python-dotenv==1.0.1
                pydantic==2.6.1
                """;
        Files.writeString(dir.resolve("requirements.txt"), content);
    }

    private void generateEnvExample(Path dir, Long projectId) throws IOException {
        String content = """
                # AI Chatbot Server Configuration
                OPENAI_API_KEY=your-openai-api-key-here
                CHROMA_PATH=./chroma_db
                PORT=8001
                PROJECT_ID=%s
                """.formatted(projectId);
        Files.writeString(dir.resolve(".env.example"), content);
    }

    private void generateDockerfile(Path dir) throws IOException {
        String content = """
                FROM python:3.11-slim
                
                WORKDIR /app
                
                COPY requirements.txt .
                RUN pip install --no-cache-dir -r requirements.txt
                
                COPY . .
                
                EXPOSE 8001
                
                CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
                """;
        Files.writeString(dir.resolve("Dockerfile"), content);
    }

    private void generateReadme(Path dir, Project project) throws IOException {
        String content = """
                # AI Chatbot - %s
                
                Auto-generated chatbot server trained on: **%s**
                
                ## Quick Start
                
                ### 1. Install dependencies
                ```bash
                pip install -r requirements.txt
                ```
                
                ### 2. Configure environment
                ```bash
                cp .env.example .env
                # Edit .env and add your OPENAI_API_KEY
                ```
                
                ### 3. Run server
                ```bash
                python main.py
                ```
                
                ### 4. Test
                ```bash
                curl -X POST http://localhost:8001/chat \\
                  -H "Content-Type: application/json" \\
                  -d '{"message": "What is this website about?"}'
                ```
                
                ## Widget Integration
                
                Add this to your website:
                ```html
                <script src="chatbot-widget.js"></script>
                <script>
                  ChatWidget.init({ serverUrl: 'http://localhost:8001' });
                </script>
                ```
                
                ## Docker
                ```bash
                docker build -t chatbot .
                docker run -p 8001:8001 --env-file .env chatbot
                ```
                """.formatted(project.getName(), project.getWebsiteUrl());
        Files.writeString(dir.resolve("README.md"), content);
    }

    private void generateWidget(Path dir) throws IOException {
        Path widgetDir = dir.resolve("widget");
        Files.createDirectories(widgetDir);

        String widgetJs = """
                /**
                 * Instant Chatbot Widget - Embeddable Chatbot
                 */
                (function() {
                  const ChatWidget = {
                    config: { serverUrl: 'http://localhost:8001' },
                
                    init: function(options) {
                      this.config = { ...this.config, ...options };
                      this.createWidget();
                      this.attachEvents();
                    },
                
                    createWidget: function() {
                      // Build metadata - Spring AI Document metadata must be String values
                      const container = document.createElement('div');
                      container.id = 'Instant Chatbot-widget';
                      container.innerHTML = `
                        <div id="Instant Chatbot-toggle" style="
                          position: fixed; bottom: 24px; right: 24px; width: 60px; height: 60px;
                          border-radius: 50%; background: linear-gradient(135deg, #667eea, #764ba2);
                          cursor: pointer; display: flex; align-items: center; justify-content: center;
                          box-shadow: 0 4px 20px rgba(102,126,234,0.4); z-index: 10000;
                          transition: transform 0.3s ease;">
                          <svg width="28" height="28" fill="white" viewBox="0 0 24 24">
                            <path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2z"/>
                          </svg>
                        </div>
                        <div id="Instant Chatbot-panel" style="
                          display: none; position: fixed; bottom: 96px; right: 24px;
                          width: 380px; height: 520px; border-radius: 16px; overflow: hidden;
                          background: #1a1a2e; box-shadow: 0 8px 40px rgba(0,0,0,0.3);
                          z-index: 10000; font-family: 'Inter', sans-serif;
                          display: none; flex-direction: column;">
                          <div style="padding: 16px 20px; background: linear-gradient(135deg, #667eea, #764ba2);
                            color: white; font-weight: 600; font-size: 16px;">
                            AI Assistant
                          </div>
                          <div id="Instant Chatbot-messages" style="flex: 1; overflow-y: auto; padding: 16px;"></div>
                          <div style="padding: 12px; border-top: 1px solid #2a2a4a; display: flex; gap: 8px;">
                            <input id="Instant Chatbot-input" type="text" placeholder="Ask a question..."
                              style="flex:1; padding: 10px 14px; border-radius: 8px; border: 1px solid #3a3a5a;
                              background: #16163a; color: white; outline: none; font-size: 14px;"/>
                            <button id="Instant Chatbot-send" style="
                              padding: 10px 16px; border-radius: 8px; border: none;
                              background: linear-gradient(135deg, #667eea, #764ba2);
                              color: white; cursor: pointer; font-weight: 600;">Send</button>
                          </div>
                        </div>`;
                      document.body.appendChild(container);
                    },
                
                    attachEvents: function() {
                      const toggle = document.getElementById('Instant Chatbot-toggle');
                      const panel = document.getElementById('Instant Chatbot-panel');
                      const input = document.getElementById('Instant Chatbot-input');
                      const send = document.getElementById('Instant Chatbot-send');
                
                      toggle.addEventListener('click', () => {
                        panel.style.display = panel.style.display === 'none' ? 'flex' : 'none';
                      });
                
                      send.addEventListener('click', () => this.sendMessage());
                      input.addEventListener('keypress', (e) => {
                        if (e.key === 'Enter') this.sendMessage();
                      });
                    },
                
                    sendMessage: async function() {
                      const input = document.getElementById('Instant Chatbot-input');
                      const messages = document.getElementById('Instant Chatbot-messages');
                      const msg = input.value.trim();
                      if (!msg) return;
                
                      this.addMessage(msg, 'user');
                      input.value = '';
                
                      try {
                        const res = await fetch(this.config.serverUrl + '/chat', {
                          method: 'POST',
                          headers: { 'Content-Type': 'application/json' },
                          body: JSON.stringify({ message: msg })
                        });
                        const data = await res.json();
                        this.addMessage(data.answer, 'bot');
                      } catch (err) {
                        this.addMessage('Sorry, something went wrong.', 'bot');
                      }
                    },
                
                    addMessage: function(text, sender) {
                      const messages = document.getElementById('Instant Chatbot-messages');
                      const div = document.createElement('div');
                      div.style.cssText = `margin-bottom: 12px; padding: 10px 14px; border-radius: 12px;
                        max-width: 85%; font-size: 14px; line-height: 1.5; word-wrap: break-word;
                        ${sender === 'user'
                          ? 'background: linear-gradient(135deg, #667eea, #764ba2); color: white; margin-left: auto;'
                          : 'background: #2a2a4a; color: #e0e0e0;'}`;
                      div.textContent = text;
                      messages.appendChild(div);
                      messages.scrollTop = messages.scrollHeight;
                    }
                  };
                
                  window.ChatWidget = ChatWidget;
                })();
                """;
        Files.writeString(widgetDir.resolve("chatbot-widget.js"), widgetJs);
    }

    private void generateDeployScript(Path dir) throws IOException {
        String content = """
                #!/bin/bash
                # Deploy script for the AI Chatbot
                
                echo "Starting AI Chatbot deployment..."
                
                # Check for .env file
                if [ ! -f .env ]; then
                    echo "Error: .env file not found. Copy .env.example to .env and add your API key."
                    exit 1
                fi
                
                # Install dependencies
                echo "Installing dependencies..."
                pip install -r requirements.txt
                
                # Start server
                echo "Starting chatbot server..."
                uvicorn main:app --host 0.0.0.0 --port ${PORT:-8001}
                """;
        Files.writeString(dir.resolve("deploy.sh"), content);
    }

    private void createZip(Path sourceDir, Path zipFile) throws IOException {
        try (ZipOutputStream zos = new ZipOutputStream(new FileOutputStream(zipFile.toFile()))) {
            Files.walk(sourceDir)
                    .filter(path -> !Files.isDirectory(path))
                    .forEach(path -> {
                        ZipEntry entry = new ZipEntry(sourceDir.getParent().relativize(path).toString());
                        try {
                            zos.putNextEntry(entry);
                            Files.copy(path, zos);
                            zos.closeEntry();
                        } catch (IOException e) {
                            throw new UncheckedIOException(e);
                        }
                    });
        }
    }

    private void deleteDirectory(Path dir) {
        try {
            Files.walk(dir)
                    .sorted((a, b) -> b.compareTo(a))
                    .forEach(path -> {
                        try { Files.delete(path); }
                        catch (IOException ignored) {}
                    });
        } catch (IOException ignored) {}
    }

    /**
     * Retrieves the file system path for a previously generated chatbot ZIP.
     *
     * @param projectId the project identifier
     * @return the Path to the ZIP file
     * @throws ResourceNotFoundException if no package has been generated for the project
     */
    public Path getZipPath(Long projectId) {
        GeneratedBot bot = generatedBotRepository.findByProjectId(projectId)
                .orElseThrow(() -> new ResourceNotFoundException("Generated bot not found"));
        return Paths.get(bot.getZipFilePath());
    }
}
